name: lab2-tests

on: 
    push

jobs: 
    test:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: haskell/actions/setup@v2
              with:
                  ghc-version: '9.4'
                  cabal-version: '3.8'
            
            - name: Install dependencies
              run: |
                  stack build --test --bench --no-run-tests --no-run-benchmarks
                  stack build hlint
                  stack build ormolu
                  
            - name: Run tests
              run: stack test
              
            - name: Run HLint
              run: stack exec -- hlint .
              
            - name: Check formatting with Fourmolu
              run: |
                  stack exec -- ormolu --mode check .
